name: Autograding Tests

on:
  push:
  workflow_dispatch:
  repository_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dar permissão de execução ao script
        run: chmod +x ./check-css.sh

      - name: Executar verificação de CSS
        run: ./check-css.sh

      - name: Reportar resultados
        uses: classroom-resources/autograding-grading-reporter@v1
